### PR TITLE
[N-mr1] Use SystemProperties.getInt() method for PREF_ADB_NETWORK_READ

### PR DESCRIPTION
**Pull request by abioteau**

### CODE REVIEW

**Comment by jerpelea** [comment]
@abioteau 
ERROR: /android/packages/apps/ExtendedSettings/src/sonyxperiadev/extendedsettings/ExtendedSettingsFragment.java:249.24: The method getSystemService(Class<UserManager>) is undefined for the type ExtendedSettingsFragment

**Comment by jerpelea** [comment]
I reseted the tree untill a proper fix is pushed !

**Comment by abioteau** [comment]
@jerpelea i will fix it quickly. Sorry for the disruption.

**Comment by jerpelea** [comment]
please push again after fixing the issues

**Pull request merged**
