### PR TITLE
ES: Squashed commit of translations

### PR DESCRIPTION
**Pull request by Myself5**
Thanks to the users of CarbonROM that found our crowdin and helped.

### CODE REVIEW

**Comment by jerpelea** [comment]
can someone verify this translation?

**Comment by bartcubbins** [comment]
@jerpelea I would have slightly adjusted the ukrainian language, but in general it's all right

**Comment by jerpelea** [comment]
please fix it

**Comment by bartcubbins** [comment]
will do this asap

**Pull request closed without merging**
