### PR TITLE
Add Slovak Translation

### PR DESCRIPTION
**Pull request by Gouster4**

### CODE REVIEW

**Comment by MarijnS95** [comment]
Were these strings translated with Android Studio by any chance?

https://stackoverflow.com/questions/20121246/localizations-for-abc-strings-from-com-android-supportappcompat-v7-appeared

You should not need to translate any of the `abc_` strings, only those specific to ES as seen in the base strings file:

https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/blob/master/res/values/strings.xml

Please maintain proper indentation like the other translation files.

**Comment by Haxk20** [comment]
@Gouster4 Please drop the abc_ translations. And force push to your branch so you dont need 2 commits. Thank you.

**Comment by Haxk20** [comment]
@Gouster4 Please could you drop the abc_ translations ? It cant be merged without this.

**Comment by Haxk20** [comment]
@jerpelea This can be closed since #59  has been merged.

**Pull request closed without merging**
