### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by luk1337** [comment]
[ Rebased ]

**Comment by luk1337** [comment]
Rebased my both branches: patch-1 (cleanup); patch-2 (kill nougat)

**Comment by jerpelea** [comment]
you can not kill N unless we fork it for n-mr1

**Comment by luk1337** [comment]
Then maybe that's what we should do after cleanup? Having settings app with Nougat theme in Oreo just looks silly, doesn't it?

**Comment by jerpelea** [comment]
you got the new branch 
please push to both

**Pull request merged**
