### PR TITLE
Add russian translation for DRS and DispCal strings

### PR DESCRIPTION
**Pull request by bartcubbins**
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

### CODE REVIEW

**Comment by bartcubbins** [comment]
I can verify russian translation. @dani020110 can verify spanish.

**Comment by bartcubbins** [comment]
DONTMERGEME. we need to add the translation for the display whitepoint calibration

**Comment by bartcubbins** [comment]
@jerpelea translation was added for DRS and DispCal strings for russian and spanish languages.

**Comment by alviteri** [comment]
Usually the  ¡  In Spanish is not needed there

**Comment by bartcubbins** [comment]
@alviteri updated

**Comment by dani020110** [comment]
The first exclamation mark ¡ is not usually **seen** in the spanish Internet, because most people are lazy to put it when chatting, and/or are used to write like english, but it is a rule to write both
http://www.rae.es/consultas/ortografia-de-los-signos-de-interrogacion-y-exclamacion

**Comment by bartcubbins** [comment]
@dani020110 this pr was separated, because I can't verify spanish translation

**Comment by jerpelea** [comment]
is the translation ok for you?

**Comment by bartcubbins** [comment]
@jerpelea yes, russian are ok

**Pull request merged**
