### PR TITLE
[1/4] ES: Add toggle for glove mode

### PR DESCRIPTION
**Pull request by MarijnS95**
Closes https://github.com/sonyxperiadev/bug_tracker/issues/367.

### CODE REVIEW

**Comment by kholk** [comment]
The only wrong thing that I see is that you've left a choice to the user.
I don't think that we should leave any choice... we should unconditionally
FORCE the show taps option to get on (and probably off) with this setting.

The whole point is that, as you wrote in the XMLs too, some touchscreens
may show accuracy loss.. and I'm adding, some touchscreens may show
ghost touch issues when this option is ON and you use some crap phone
charger with your device and, well, not only, it can also depend on the
environmental conditions, like temperature and humidity of the air and on
how naturally oily is the person's finger (so how much oil residue it leaves
on the glass).

I cannot avoid to say:
Of course crap chargers shall never be used, but the sad reality is that,
unfortunately, people WILL use them.

**Comment by MarijnS95** [comment]
The only reason the opt-out was added (as a separate commit, to have the option to remove it) is because it changes another setting. The chances a user actually uses this _developer_ setting is very small; yet I want to alert them about it being changed.
Now if we had our own overlay showing this (which we won't, too much trouble and framework modifications), I fully agree.

**Comment by MarijnS95** [comment]
Commit removed. We still show a dialog with the warning, just in case.

**Comment by MarijnS95** [comment]
@kholk This is ready for review now, as long as you or someone else can check which path is used for every platform. Loire and Tama are in there, Nile and Ganges don't seem to have this functionality (at least not according to sysfs), and I have no idea about Tone and Yoshino.

**Comment by MarijnS95** [comment]
As a sidenote, we were also considering a QS tile, and/or a permanent icon (https://material.io/tools/icons/?search=touc&icon=touch_app&style=baseline) in the top-right status bar.

**Comment by kholk** [comment]
Adding a QS tile for it is a really really nice idea.
Besides that, we would be able to also reuse that code for other things, like a PCC/PA night mode switch in the near future.

About warning the user that we're going to enable a developer setting.. Yeah, of course, that's mandatory! The user has to be obviously aware of what's happening around! :D

**Comment by kholk** [comment]
<string name="dialog_enable_glove_mode">La modalità guanti può avere effetti negativi sulla precisione del tocco. L'opzione <i>Mostra tocchi</i> verrà abilitata per ricordarti che questa funzionalità è attiva. Questa opzione può essere disattivata manualmente in <i>Opzioni sviluppatore</i>, oppure sarà disattivata alla disattivazione di modalità guanti. </string>

Note: "oppure sarà disattivata alla disattivazione di modalità guanti" is an addition to your text saying "or it will get disabled when deactivating glove mode". I think we should make the user aware of that too also when he enables the option. 


    <string name="dialog_disable_glove_mode">La disattivazione della modalità guanti disattiverà l'opzione sviluppatore <i>Mostra tocchi</i>.</string>

Enjoy :p

**Comment by MarijnS95** [comment]
I think that goes without saying, and a message is shown when disabling too. Or are you trying to inform the user that both changes will not come through when they click cancel?

**Comment by kholk** [comment]
No the thing is simple. It's to inform the user of what's gonna happen in its entirety when the user opts in, instead of partially telling him now and then because the glove mode is supposed to be something that you use for a relatively short amount of time and that then you disable anyway.

**Comment by MarijnS95** [comment]
Pushed with the italian strings... What translation do you want for `warning`?

I'll see about the QS tile. It should be a simple copy-paste, otherwise I leave it in favor of more important things to do.

**Pull request merged**
